version: '3'
services:
  mysqlsrv:
    image:  mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'votacao_db'
      MYSQL_ROOT_PASSWORD: 'Pwd@2021'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql.votacao:/var/lib/mysql
    networks:
      - votacao-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - votacao-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - votacao-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - votacao-network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  votacao-app:
    container_name: votacao-app
    build:
      context: .
      dockerfile: Dockerfile
    image: votacao-app
    ports:
      - '8080:8080'
    networks:
      - votacao-network
    depends_on:
      - mysqlsrv
      - zookeeper
      - kafka
      - kafdrop

volumes:
  mysql.votacao:

networks:
  votacao-network:
    driver: bridge