spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:votacao_db;DATABASE_TO_UPPER=false;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

kafka.server: localhost:9092