spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/votacao_db
    driver-class-name: com.mysql.jdbc.Driver